# -*- coding: utf-8 -*-
"""KT tasks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Ouqpf0rqOrbBkvM4aF9f2LB-dQfxSY6
"""

import pandas as pd
from pyspark.sql import SparkSession
from pyspark.sql import functions as F

from google.colab import drive
drive.mount('/content/drive')

spark = SparkSession.builder.appName('Tasks').getOrCreate()

pd_df = pd.read_excel(r'/content/drive/MyDrive/Colab Notebooks/Financial Sample_kt.xlsx')

type(pd_df)

# converting pandas df to pyspark df
df = spark.createDataFrame(pd_df)

type(df)

df.printSchema()

# 2 replacing column spaces with _

print(df.columns)

df = df.withColumnRenamed('Discount Band', 'Discount_Band').withColumnRenamed('Units Sold', 'Units_Sold')\
.withColumnRenamed('Manufacturing Price', 'Manufacturing_Price').withColumnRenamed('Sale Price', 'Sale_Price').withColumnRenamed('Month Name', 'Month_Name')

df.show(2)

# 3 concat manufacturer and product with seperator /

df = df.withColumn(
    'concatWithSep',
    F.concat_ws('/', F.col('Manufacturer'), F.col('Product'))
)
df.show(2)

# 4 round off units sold

df.select('Units_Sold', F.ceil(F.col('Units_Sold'))).show(2)

# add new column as month number

df = df.withColumn('Month_number', F.month('Date'))
df.show(10)

# remove $ from discounts and add USD

df = df.withColumn(
    'DiscountsNew',
    F.concat(F.col('Discounts'), F.lit(' USD'))
)
df.show(5)

\


